### ISSUE TITLE
Non-RNA-seq data, and can we link features from input to output?

### ISSUE THREAD

**Issue by koenvandenberge** [CenterForStatistics-UGent/SPsimSeq#15]
Hi Alemu and Stijn,

I'm thinking of possibly using this framework to simulate (bulk) ATAC-seq data.
I have a 'null dataset' which consists of 10 samples with no systematic biological variation between them, and I was wondering how you'd recommend to simulate. It seems like setting `group=NULL` would make sense to use all 10 samples to estimate the feature-wise distribution. I did not read about guidelines regarding dataset size, would you consider 10 samples to be insufficient?

Also, it seems like `SPsimSeq` is selecting candidate DE features itself, which I am not expecting. Would this be problematic?

Furthermore, for my project it is important that I get to link the input features from the real dataset to the output features from the simulated data, as there are covariates associated with each feature that I'm interested in evaluating further downstream (for example, this could be analogous to gene length in RNA-seq). Is this possible using `SpsimSeq`?

Thanks!
Koen

**Comment by AlemuTA** [comment]
Hi Koen,

You can simulate null features by specifying ```group=NULL``` or ```pDE=0```. 10 samples are I believe sufficient to semi-parametrically construct the densities provided that the data is not very noisy.  ```SPsimSeq``` indeed can select DE features but you can disable it and input your list of candidate null features using the argument ```cand.DE.genes```, which is NULL by default and when it is NULL ```SPsimSeq``` runs the DE selection algorithm in the package. Therefore, for your case simply leave it NULL because you already make```group=NULL``` and ```pDE=0```.  However, this option is very useful if you want to simulate for n' features where the source data has n features and n' < n. The DE selection algorithm will make only random sampling of n' null features from n of them. Or instead, make ```cand.DE.genes = list(null.genes=rownames(X), nonnull.genes=NULL)```, where X is your source data matrix with row names are the feature names. This option is particularly useful when n=n'.

For the second question, yes, the ```SPsimSeq``` output (specifically the rowdata info) includes the source feature used for a particular simulated feature, so that you can link it to its 'background' covariate like as you said the gene length for RNA-seq data. This info has a column name 'source.ID' in row.data output.

Let me know if it works or not for your particular assay. 

Regards,
Alemu
