### ISSUE TITLE
No DE detected, error in sample.int(length(x), size, replace, prob): invalid first argument. 

### ISSUE THREAD

**Issue by Zanvine-gitcode** [CenterForStatistics-UGent/SPsimSeq#3]
Hello, 
I'm trying to run some simulations on bulk & single-cell RNAseq data. 

I try both my single cell & bulk RNAseq data, but I get the error: 
Note: The number of DE genes detected in the source data is 0 and the number of DE genes required to be included in the simulated data is 200. Therefore, candidiate DE genes are sampled with replacement.
Error in sample.int(length(x), size, replace, prob) : 
  invalid first argument

Each time. 

I tried with the following arguments. 
test <- SPsimSeq::SPsimSeq(n.sim = 1, s.data =single.cell.sce, verbose = T,lfc.thrld = 0.25, llStat.thrld = 3)

test <- SPsimSeq::SPsimSeq(n.sim = 1, s.data =Bulk.sce, verbose = T,lfc.thrld = 0.25, llStat.thrld = 3)

test <- SPsimSeq::SPsimSeq(n.sim = 1, s.data =Bulk.sce, verbose = T)
test <- SPsimSeq::SPsimSeq(n.sim = 1, s.data =single.cell.sce, verbose = T)

Many thanks in advance for any advice.

**Comment by AlemuTakele** [comment]
Hi Zaninfmcs,

This error message happens when SPsimSeq could not find any candidate DE genes in the source data you used. The message particularly came from the ```sample()``` function when it could not find a single candidate DE gene to sample from. There are two possible solutions

1. make sure that your source data has any DE genes
2. I can see that you tried to lower the LFC and LL thresholds, and again try to lower the T-statistic threshold (e.g. t.thrld=1.5), which is 2.5 by default. However, the later one will result in a set of DE genes with less statistical confidence on the DE.

Generally, we are updating the current version that includes this issue. It will be released in a few days.

Alemu

**Comment by AlemuTA** [comment]
Hi Zaninfmcs,
The new version  SPsimSeq (v2.0.0) is released, and perhaps you can try it.

Alemu

**Comment by Zanvine-gitcode** [comment]
Hi Alemu, 

Thank you both for your replies, 

I'll try the updated version, looking forward to it :-) 

Best,
Zanvine
